CREATE TABLE [Games]
(
	[GameId] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Author] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(2000) NOT NULL,
	[Genre] NVARCHAR(50) NOT NULL,
	[Price] DECIMAL(16,2) NOT NULL,
	[ImageData] VARBINARY (MAX) NULL,
	[ImageMimeType] VARCHAR(50) NULL
)